import { Colors } from './colors';
import { StyleSheet } from 'react-native';

export const globalStyle = StyleSheet.create({
  alignSelfCenter: {alignSelf: 'center'},
  alignItemsEnd: {alignItems: 'flex-end'},
  alignSelfEnd: {alignSelf: 'flex-end'},
  flexRow: {flexDirection: 'row'},
  rowWrap: {flexDirection: 'row', flexWrap: 'wrap'},
  flexSpaceBetween: {flexDirection: 'row', justifyContent: 'space-between'},
  spaceBetween: {justifyContent: 'space-between'},
  flexColumn: {flexDirection: 'column'},
  flexCenter: {alignItems: 'center', justifyContent: 'center'},
  justifyCenter: {justifyContent: 'center'},
  pBottom30: {paddingBottom: 30},
  pTop10: {paddingTop: 10},
  pTop24: {paddingTop: 24},
  width100: {width: '100%'},
  widthAuto: {width: 'auto'},
  pVertical20: {
    paddingVertical: 20,
  },
  pVertical10: {
    paddingVertical: 10,
  },
  flexRowAlignCenter: {flexDirection: 'row', alignItems: 'center'},
  flexRowAlignStart: {flexDirection: 'row', alignItems: 'flex-start'},
  flexColumnAlignCenter: {flexDirection: 'column', alignItems: 'center'},
  marginVertical5: {
    marginVertical: 5,
  },
  marginVertical8: {
    marginVertical: 8,
  },
  marginVertical10: {
    marginVertical: 10,
  },
  marginVertical13: {marginVertical: 13},
  marginVertical20: {
    marginVertical: 20,
  },
  marginVertical24: {marginVertical: 24},
  marginVertical32: {
    marginVertical: 32,
  },
  paddingTop100: {paddingTop: 100},
  paddingTop16: {paddingTop: 16},
  paddingBottom8: {paddingBottom: 8},
  paddingBottom16: {paddingBottom: 16},
  alignCenter: {alignItems: 'center'},
  center: {alignItems: 'center', justifyContent: 'center'},
  marginTop10: {
    marginTop: 10,
  },
  marginTop12: {marginTop: 12},
  marginTop4: {
    marginTop: 4,
  },
  marginTop8: {
    marginTop: 8,
  },
  marginTop13: {
    marginTop: 13,
  },
  marginB10: {marginBottom: 10},
  margin24: {margin: 24},
  margin12: {margin: 16},
  marginB45: {marginBottom: 45},
  marginB15: {marginBottom: 15},
  marginB13: {marginBottom: 13},
  marginB20: {marginBottom: 20},
  marginB24: {marginBottom: 24},
  marginB50: {marginBottom: 50},
  marginTop60: {marginTop: 60},
  marginTop24: {marginTop: 24},
  marginTop32: {marginTop: 32},
  marginTop20: {marginTop: 20},
  marginTop23: {marginTop: 23},
  marginTop40: {marginTop: 40},
  marginTop50: {marginTop: 50},
  marginTop59: {marginTop: 59},
  marginTop15: {marginTop: 15},
  marginTop16: {marginTop: 16},
  marginLeft0: {marginLeft: 0},
  marginLeft8: {marginLeft: 8},
  marginLeft10: {marginLeft: 10},
  marginLeft16: {marginLeft: 16},
  marginLeft20: {marginLeft: 20},
  marginLeft24: {marginLeft: 24},
  marginLeft50: {marginLeft: 50},
  padding24: {padding: 24},
  paddingLeft20: {paddingLeft: 20},
  paddingRight20: {paddingRight: 20},
  marginRight0: {marginRight: 0},
  marginRight8: {marginRight: 8},
  marginRight10: {marginRight: 10},
  marginRight20: {marginRight: 20},
  marginRight24: {marginRight: 24},
  marginHorizontal0: {marginHorizontal: 0},
  marginHorizontal24: {marginHorizontal: 24},
  marginHorizontal25: {marginHorizontal: 25},
  marginHorizontal8: {marginHorizontal: 8},
  marginHorizontal10: {marginHorizontal: 10},
  marginHorizontal16: {marginHorizontal: 16},
  marginVertical18: {marginVertical: 18},
  paddingHorizontal8: {paddingHorizontal: 8},
  paddingHorizontal16: {paddingHorizontal: 16},
  paddingVertical8: {paddingVertical: 8},
  paddingVertical24: {paddingVertical: 24},
  flex1: {flex: 1},
  flexshrink1: {flexShrink: 1},
  width50: {
    width: '50%',
  },
  textCenter: {
    textAlign: 'center',
  },
  positionRelative: {
    position: 'relative',
  },
  appContainer: {flex: 1, backgroundColor: Colors.white},
  activeTabBorder: {
    height: 4,
    width: 35,
    backgroundColor: Colors.dark_blue,
    borderRadius: 99,
    marginTop: 2,
  },
  tabProfile:{height:30,width:30,borderRadius:99}
});
